# Generated by Django 2.2.6 on 2019-11-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_estimate',
            field=models.IntegerField(verbose_name='time estimate (hours)'),
        ),
    ]
