# Generated by Django 2.2.6 on 2019-11-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20191105_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_estimate',
            field=models.DurationField(verbose_name='time estimate'),
        ),
    ]
