# Generated by Django 2.2.6 on 2019-11-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20191109_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_estimate',
            field=models.TimeField(verbose_name='time estimate'),
        ),
    ]
