# Generated by Django 2.2.6 on 2019-11-11 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20191111_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2019, 11, 11, 17, 16, 23, 694744, tzinfo=utc), verbose_name='due time'),
            preserve_default=False,
        ),
    ]
