# Generated by Django 2.2.6 on 2019-11-11 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20191111_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=datetime.time(17, 43, 41, 261721), verbose_name='due time'),
        ),
    ]
