# Generated by Django 2.2.6 on 2019-11-12 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_auto_20191112_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=datetime.time(16, 26, 55, 595526), verbose_name='due time'),
        ),
    ]
