# Generated by Django 2.2.6 on 2019-11-12 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_auto_20191112_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 12, 17, 8, 21, 998659, tzinfo=utc), verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2019, 11, 12, 17, 8, 21, 998703, tzinfo=utc), verbose_name='due time'),
        ),
    ]
