# Generated by Django 2.2.6 on 2019-12-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20191201_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='day',
            field=models.IntegerField(),
        ),
    ]
