# Generated by Django 3.0.1 on 2020-01-01 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_auto_20191201_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='override_routine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routine',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='override_routine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('associated_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Event')),
                ('associated_routine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Routine')),
                ('associated_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
        ),
    ]
