# Generated by Django 3.0.1 on 2020-01-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20200101_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
