# Generated by Django 3.0.1 on 2020-01-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_auto_20200103_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='associated_type',
            field=models.IntegerField(choices=[(0, 'task'), (1, 'event'), (2, 'routine')], default=0, verbose_name='type'),
            preserve_default=False,
        ),
    ]
