# Generated by Django 3.0.2 on 2020-03-08 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_timeslot_associated_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('tasks_todo', models.IntegerField(verbose_name='tasks todo')),
                ('tasks_overdue', models.IntegerField(verbose_name='tasks overdue')),
                ('tasks_done', models.IntegerField(verbose_name='tasks done')),
                ('tasks_done_recent', models.IntegerField(verbose_name='tasks done recent')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='override_routine',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_on_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_time',
            field=models.DateTimeField(null=True, verbose_name='completion time'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='time spent'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 3, 8), verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=datetime.time(16, 8, 46, 346318), verbose_name='due time'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='associated_type',
            field=models.CharField(choices=[('T', 'task'), ('E', 'event'), ('R', 'routine')], max_length=200, verbose_name='type'),
        ),
    ]
