# Generated by Django 3.0.2 on 2020-01-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_timeslot_associated_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='associated_type',
            field=models.CharField(choices=[('T', 'task'), ('E', 'event'), ('R', 'routine')], max_length=200, verbose_name='type'),
        ),
    ]
