# Generated by Django 3.0.2 on 2020-03-08 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_auto_20200308_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completion time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=datetime.time(16, 14, 27, 884901), verbose_name='due time'),
        ),
    ]
