# Generated by Django 3.0.2 on 2020-03-08 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_auto_20200308_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=datetime.time(18, 20, 24, 587518), verbose_name='due time'),
        ),
    ]
