# Generated by Django 3.0.2 on 2020-03-20 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_auto_20200312_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 3, 20), verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=datetime.time(15, 50, 0, 314442), verbose_name='due time'),
        ),
    ]
