# Generated by Django 3.0.2 on 2020-03-22 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_auto_20200322_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=datetime.time(19, 47, 56, 164936), verbose_name='due time'),
        ),
    ]
